version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - chmod +x build.sh
      #  - ./build.sh test-unit
      - ./build.sh deploy dev
      - ./build.sh test-e2e
